version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'tiny_url'
      MYSQL_USER: 'useradmin'
      MYSQL_PASSWORD: 'code2019'
      MYSQL_ROOT_PASSWORD: 'rootcode2019'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
